### ISSUE TITLE
Add prime8s.xyz to list of instances

### ISSUE THREAD

**Issue by charwrangler404** [maltfield/awesome-lemmy-instances#10]
Hello! I am the owner of this instance. I'll do my best to answer any questions you have. Here's the stats for you, if you don't want to pull them yourself. Feel free to verify them, of course.

https://prime8s.xyz 
NU - Yes
NC - Currently No, will open up soon
Fed - Yes
Adult - No
Users - 3-4

This instance is primarily art, technology, and gaming based. I'm happy to answer any questions you have.

**Comment by maltfield** [comment]
Hi @charwrangler404, thanks for the submission.

Unfortunately I do *not* maintain this list manually. New Instances are discovered automatically using the rust tool lemmy-stats-crawler:

 * https://github.com/LemmyNet/lemmy-stats-crawler

I see that your instance is federating and the API is exposed, which is good:

 * https://prime8s.xyz/api/v3/site

Once users from other instances subscribe to your communities, it should get added automatically

**Comment by maltfield** [comment]
Edit: I see it's already on the list ;)
