### ISSUE TITLE
Include metric for total lifetime of instance 

### ISSUE THREAD

**Issue by calculuschild** [maltfield/awesome-lemmy-instances#13]
When choosing a good instance to join, I don't want to pick a server that has only been around for 2 days, because 100% uptime is still meaningless at that point.

Any way the recommendations could take the total lifetime of the instance into account? I.e., check if it's been around for at least a month or more? And display that number in the table?

I'm assuming that each instance is already alive for at least 1 month because of the active monthly users number, but I think it would add some legitimacy and confidence for scared Reddit refugees trying to find something stable.

**Comment by maltfield** [comment]
Thanks for the suggestion!

Yep, this data is already tracked here

 * https://fedidb.org/software/lemmy

Looks like they have an API, but we'd have to figure out how to use it. If you can figure out how to query the above site using cURL and post the command here to this issue, it would speed-up implementation of this feature request :)

**Comment by jldevine009** [comment]
Hi, I created a simple python script to get the first_seen time of each domain from that API. Hopefully this is helpful. You could of course do this with curl and grep your desired info if you so chose.
```Python
import requests
from requests.exceptions import HTTPError

try:
from datetime import date, datetime
import requests
from requests.exceptions import HTTPError

try:
    response = requests.get('https://api.fedidb.org/v1/servers')
    json_response = response.json()
    if response.status_code == 200:
        # unpacking tuples
        domains_data, _, _ = json_response.items()
        domains = domains_data[1]
        for domain in domains:
            formatted_time = datetime.strptime(domain["first_seen_at"], "%Y-%m-%dT%H:%M:%S.%fZ")
            template_str = "DOMAIN: {} FIRST_SEEN: {}".format(domain["domain"], formatted_time)
            print(template_str)
    elif response.status_code != 200:
        print(f'non-200 response : {response.status_code}')

except HTTPError as http_err:
    print(f'HTTP error occurred: {http_err}')
except Exception as err:
    print(f'Other error occurred: {err}')

```

output:
```
DOMAIN: mastodon.social FIRST_SEEN: 2021-03-30 20:10:40
DOMAIN: mstdn.jp FIRST_SEEN: 2021-03-30 20:10:41
DOMAIN: mastodon.cloud FIRST_SEEN: 2021-03-30 20:10:42
DOMAIN: misskey.io FIRST_SEEN: 2021-03-21 07:02:57
DOMAIN: mstdn.social FIRST_SEEN: 2021-03-30 20:10:42
DOMAIN: mastodon.online FIRST_SEEN: 2021-03-30 20:10:42
DOMAIN: mastodon.world FIRST_SEEN: 2021-03-21 07:01:16
DOMAIN: mas.to FIRST_SEEN: 2021-03-21 07:03:05
DOMAIN: micro.blog FIRST_SEEN: 2021-03-21 06:54:12
DOMAIN: gc2.jp FIRST_SEEN: 2022-12-30 23:02:35
```

**Comment by maltfield** [comment]
This is finished (see MO = Months Online) field. I've also adjusted the "recommened instances" algorithm to only show instances that have MO >= 2.

Annonunced on /c/lemmy here:

 * https://monero.town/post/445324
