### ISSUE TITLE
Add information to readme.md on how often data is updated

### ISSUE THREAD

**Issue by Raspire52** [maltfield/awesome-lemmy-instances#18]
Hi,

I am developing my own Lemmy related application and would like to use your csv file as a source of truth. Thank you very much for this data as it is very helpful, especially including the data on which instances allow downvotes or not.

How often is the data updated, and are you updating it automatically or manually?

If possible could the date csv was created be added to the file?

many thanks

**Comment by Raspire52** [comment]
Read the closed issues, I understand how you source your data now. Adding this to the readme along with the time / date data was pulled, as well as adding the time and date data was pulled to the cab would be most helpful. Thanks again

**Comment by maltfield** [comment]
Thanks for the great suggestion.

May I ask which service you're working-on? I'll add it to my recommended links. And if you wouldn't mind doing the same?

**Comment by Raspire52** [comment]
I'm trying to develop a user allowlist database, based on their total karma standing on their chosen instance with the age of their account. The end goal is a tool for some admins to use, to only allow "verified" users to signup to their communities. Similar to how you people need X account karma on reddit before allowing to post in some subreddits. 

The idea is that, for instances which are more sensitive to nefarious actors, bots and spamming, such as "lemmy_nsfw", they don't allow new signups on their instance unless the user is cleared in the allowlist database. 

Lemmy_nsfw is my example as some other instances have NSFW disabled which means that most content is hidden from their users and so users looking for that sort of content have to create a separate account on the instance anyway. It also works for instances like beehaw that have recently de-federated themselves from other instances in an effort to shut out spam.

My idea is definitely work-in-progress and not fully formed, it requires further discussion. I now realise that for instances that don't allow downvotes, their users cannot be verified using this service. I'm also yet to work out some of the intricacies on how this service couldn't be used by an imposter / fraudulently. I think email verification will be required to combat this along with supplying some extra account information from the users on a user front end or within the sign up area of the new Lemmy instance they are trying to access.

Hopefully the service tool will contribute to keeping spaces safe for all, but especially ethnic minorities and the LGBTQIA+ community within the Lemmyverse.

And yes of course, I will add your data and where I sourced it to my project.

**Comment by Raspire52** [comment]
It still early days I'll share a link with you when I make it public in a couple weeks

**Comment by maltfield** [comment]
> I'm trying to develop a user allowlist database, based on their total karma standing on their chosen instance with the age of their account. The end goal is a tool for some admins to use, to only allow "verified" users to signup to their communities. Similar to how you people need X account karma on reddit before allowing to post in some subreddits.
> 
> The idea is that, for instances which are more sensitive to nefarious actors, bots and spamming, such as "lemmy_nsfw", they don't allow new signups on their instance unless the user is cleared in the allowlist database.

Well that sounds like a dystopia that makes it **hard for humans** who are new users to contribute content, but **easy for AI bots** who are new users to contribute content.

Why would you *want* to make it hard for humans but easy for bots?

>  I think email verification will be required to combat this along with supplying some extra account information from the users 

Well now you just need their phone number, address, date-of-birth, and credit-card number to make it more dystopic for at-risk users who need anonymity!

We've had a very effective tool to rate-limit spam for decades

 * https://en.wikipedia.org/wiki/Hashcash

**Comment by Raspire52** [comment]
Fair point, it's not my intention to make it easy for bots. Mainly to stop spam whilst moderation has yet to take off on Lemmy. 

Will give it a think and see how something like hashcash can be implemented.

**Comment by maltfield** [comment]
Looks like there's already some implementations of HashCash in TypeScript on GitHub:

 * https://github.com/search?q=hashcash++language%3ATypeScript&type=Repositories&ref=advsearch&l=TypeScript&l=

**Comment by maltfield** [comment]
I'm now appending a timestamp in (ISO 8601 format) to the end of the README. I may change the words around the timestamp, so if you want to robustly scrape it from the README, I recommend that you:

1. Do a regex search for ISO 8601 timestamps across the entire `README.md` file
2. Grab the last result from [1]

^ That *should* always get you the time that the data was last generated

**Comment by Raspire52** [comment]
Ok thanks for working on this, much appreciated

**Comment by maltfield** [comment]
@Raspire52 see https://github.com/LemmyNet/lemmy/issues/3204
