### ISSUE TITLE
Prevent the auto push workflow from flooding the history with commits

### ISSUE THREAD

**Issue by JediMaster25** [maltfield/awesome-lemmy-instances#22]
To prevent the auto push workflow from flooding the history with commits, you can use the `git commit --amend` command to modify the most recent commit without creating a new one, and push the changes with the `--force` flag. This way, you'll overwrite the latest commit instead of creating a new one, maintaining a cleaner commit history.

Here's an example of how to do it:

1. Make your changes in the repository.
2. Use `git add` to stage the changes.
3. Run `git commit --amend --no-edit` to modify the latest commit without changing its message.
4. Push the changes with `git push --force`.

Please note that using `--force` can be dangerous as it may overwrite other people's work if you're collaborating with others. Make sure to communicate with your team when using this approach, or consider using `--force-with-lease` instead, which only overwrites the remote branch if it's at the same commit as your local copy.

**Comment by maltfield** [comment]
Don't you think it's a feature for folks to be able to see all the changes and diff the updates hour-by-hour?

Also, the commit history of the `main` branch would be useless anyway. If someone wants to view development changes, they'd see our `dev` branch.
