### ISSUE TITLE
[ADD INSTANCE] ZeroBytes - Discuss about everything :)

### ISSUE THREAD

**Issue by 0bytes0** [maltfield/awesome-lemmy-instances#24]
zerobytes.monster

Discuss about everything :)

Your personal frontpage. Come here to check in with your favorite communities.

🍿 📺 🎵 🎮 📗 📱

Rules:

1. Please be kind and helpful to one another.

2. No racism, sexism, ableism, homophobia, transphobia, spam.

3. Linking to piracy sites is fine, but please keep links directly to pirated content in DMs.

4. Self-Promotion is fine as long as you don’t spam, and the community you’re in allows it.

5. Please mark all NSFW communities / posts, and keep in mind we will ban users who post loli/shota, bestiality, CSAM or NSFL content.

**Comment by maltfield** [comment]
Hi, thanks for your issue but instances are *not* added manually.

As your instances begins to federate and your API is publicly available, it will get added automatically

 * https://zerobytes.monster/api/v3/site
