### ISSUE TITLE
Include lists of instances of Reddit communities now on alternative platforms

### ISSUE THREAD

**Issue by ruffsl** [maltfield/awesome-lemmy-instances#25]
In addition to the existing instance/community index sites, it may be worthwhile to also link migration lists or mapping indexes for folks trying to find similar communities to previous subreddits. E.g:

- https://sub.rehab/

or

- https://www.quippd.com/writing/2023/06/15/unofficial-subreddit-migration-list-lemmy-kbin-etc.html
- https://redditmigration.com/

**Comment by maltfield** [comment]
This is a great idea, thanks. I wasn't aware of those sites.

Adding now; please check back in a few hours and let me know if there's any more resources I should add.

**Comment by ruffsl** [comment]
Not sure if this is too off topic for your awesome list, but there are also some neat uses of Monkey scripts to alter the CSS of instances to replicate the look of old.reddit:

- YSK how to theme Lemmy’s UI to replicate old.reddit’s compact layout using Monkey scripts
  - https://lemmy.world/post/375039

I've seen from comments across lemmy and kbin communities that the different and unfamiliar UI was a common lement shared across web users.
