### ISSUE TITLE
One of the top recommended instances no longer exists: vlemmy is gone.

### ISSUE THREAD

**Issue by Theophrastvs** [maltfield/awesome-lemmy-instances#32]
It's not a all clear what happened to vlemmy.net and it's sudden departure has left many happy new lemmy users marooned, but it's dead (jim).  [Here's one](https://lemmy.ml/post/1855875) on-going inconclusive discussion of what happened.

**Comment by andy5995** [comment]
I'm a first time Lemmy user. I registered on vlemmy.net yesterday. It worked great. Now it's been down for at least the last 12 hours. @Theophrastvs do you know if it's permanently down?

**Comment by maltfield** [comment]
Removals will happen automatically once I unpin the version, which is not backwards compatible. I'll probably give admins a couple more weeks to upgrade.

See also

 * https://github.com/maltfield/awesome-lemmy-instances/issues/26

**Comment by jheidecker** [comment]
Fixed without changes to lemmy-stats-crawler in PR #35

**Comment by maltfield** [comment]
@jheidecker sorry but from what I can tell these changes have already been made to the `dev` branch.

As far as I can tell, I don't see how this fixes the issue that `lemmy-stats-crawler` will not return any Instances with <v0.18.0 that have `registration_mode` set to `requireapplication`

**Comment by jheidecker** [comment]
Sorry. I did not consider < 0.18 instances. The issue mentioned https://github.com/LemmyNet/lemmy-stats-crawler/issues/9#issuecomment-1612093541 is closed and doesn't sound like it will be fixed. If you want me to fix, I'd add an "old" instances csv and pull it for somewhere else (lemmyverse.net?). Given there is security vulns in those old versions nobody should be recommended to sign up with them anyway. That might seem arbitrary, but so is only recommending instances > 60 but < 1000 users.

**Comment by maltfield** [comment]
The whole reason it's pinned to an old version is because of this upstream issue. I don't think the devs are going to fix this bug, so I'm freezing it for some weeks just to allow all of the instance admins a *reasonable* amount of time to upgrade> 

I think 1-2 more weeks should suffice, then I'll merge dev into main and everything will work as-expected again (except some instances running old versions may disappear)

**Comment by maltfield** [comment]
This is blocked by https://github.com/LemmyNet/lemmy-stats-crawler/issues/9
