### ISSUE TITLE
Where is the list of instances featured in the README.md

### ISSUE THREAD

**Issue by 7heo** [maltfield/awesome-lemmy-instances#4]
I looked for it everywhere, but I didn't find it. Is it a file you have only on your local machine? Thanks :)

**Comment by maltfield** [comment]
The README file is deleted on every run. It's generated by `generate_readme.py`

The `generae_readme.py` file parses the `lemmy-stats-crawler/lemmy-stats-crawler.json` file that's generated using the rust tool lemmy-stats-crawler:

 * https://github.com/LemmyNet/lemmy-stats-crawler

The lemmy-stats-crawler is executed by the `stats-crawler.sh` script, which has a few hard-coded "seed" instances. From those, it learns about other instances from those instances and keeps going until it finds them all.
