### ISSUE TITLE
Lemmy.world missing

### ISSUE THREAD

**Issue by laurencedawson** [maltfield/awesome-lemmy-instances#42]
Looks like this update did it:

https://github.com/maltfield/awesome-lemmy-instances/commit/115c582a6a70ee775bf4953657a15eb08f930d93

**Comment by laurencedawson** [comment]
And it's back!

Leaving open as maybe there should be some check against the previous version to see if the top instance hasn't mysteriously disappeared.

**Comment by maltfield** [comment]
issue is fixed
