### ISSUE TITLE
Site not showing up

### ISSUE THREAD

**Issue by jscholz1** [maltfield/awesome-lemmy-instances#44]
Hello,

https://real.lemmy.fan (https://real.lemmy.fan/api/v3/site) doesn't seem to be appearing in the list despite being federated and having an open API.

**Comment by maltfield** [comment]
v0.19.1 has federation issues. It's probably an issue with your instance.

**Comment by maltfield** [comment]
If you still have issues, then please open an issue upstream with [lemmy-stats-crawler](https://github.com/LemmyNet/lemmy-stats-crawler), which is how this repo gets the list of instances

**Comment by citking** [comment]
> I've read that v0.19.1 has federation issues. It's probably an issue with your instance. Try downgrading to v.18.X

Ok, but seems unlikely given that many, if not most, of the instances here are 0.19.x or greater. And also, downgrading Lemmy isn't supported. 

I'll open an issue with lemmy-stats-crawler.

**Comment by citking** [comment]
Sorry, it's jscholz under a different account.
