### ISSUE TITLE
Check if instance's host is using renewables

### ISSUE THREAD

**Issue by QazCetelic** [maltfield/awesome-lemmy-instances#45]
The Green Web foundation has [an API](https://developers.thegreenwebfoundation.org/api/greencheck/v3/check-single-domain/) to look up the site's host and check whether the host uses renewable energy or not. This can also be used to add the site's host to the data set.
However, there is a minor problem with this method. It won't work on sites that use a proxy such as Cloudflare because it will judge it based on the proxy and won't account for the real host. I suggest just setting the field to `unknown` when a proxy is in use or no data about the host is found.

**Comment by maltfield** [comment]
Thanks for the suggestion :)

Besides the proxy issue (and cloudflare isn't the only DDoS fronting proxy service; there's also akamai and probably dozen others that are located outside the US to satisfy the EUR market), one of the issues I have with this approach is carbon offset greenwashing.

 * https://www.theguardian.com/environment/2024/jan/17/eu-bans-misleading-environmental-claims-that-rely-on-offsetting

**Comment by QazCetelic** [comment]
> Your organisation offsets greenhouse gas emissions caused by using electricity to provide your service/s. This can be by purchasing quality carbon offsets from a reputable provider/marketplace.
> 
> We recommend using offsets only as a last resort. If you are not able to directly purchase renewable energy, a green tariff, or renewable energy credits then offsets can be used as evidence when seeking to be a verified provider.
> 
> In other instances, you don’t know exactly how much fossil fuel energy usage you need to account for. We often see this when upstream providers do not disclose where the power used to deliver your services comes from. In this case, you can purchase offsets to make up for this.

It seems they accept carbon credits, and are a bit vague about what they accept. The API also isn't able to show whether carbon credits are used, and if so, where they are bought from. Maybe it's better to leave it out for now.
