### ISSUE TITLE
Add Uptime

### ISSUE THREAD

**Issue by maltfield** [maltfield/awesome-lemmy-instances#7]
This ticket will track the effort to add an "uptime" column to the data table that shows the user the percent of time that the server is responding.

**Comment by maltfield** [comment]
I [recently found-out](https://github.com/LemmyNet/joinlemmy-site/issues/157#issuecomment-1583035671) that the following site also has a comparison of lemmy instances (though more general than this repo's data table), and it includes uptime data:

 * https://lemmy.fediverse.observer/list

It looks like the above site is run by [David Morley](https://twitter.com/@diasporg), and the sourcecode for it can be found here:

 * https://gitlab.com/diasporg/poduptime

I used the site's "contact" tool and asked what they're using in the backend to calculate uptime, but then I discovered that they have an API that we can use to query it:

 * https://api.fediverse.observer/

I was successfully able to use the above WUI to create the following API query

```
{
  node(domain: "lemmy.ml") {
    uptime_alltime
  }
}
```

...which returned the following result

```
{
  "data": {
    "node": [
      {
        "uptime_alltime": "98.87"
      }
    ]
  }
}
```

However, I couldn't find any documentation on how to actually query the endpoint from software or CLI. I tried the following command with cURL, to no avail (there's no output/response from the server):

```
user@host:~$ echo "{
  node(domain: "lemmy.ml") {
    uptime_alltime
  }
}" | curl -X POST \
 -H "Content-Type: application/json" \
 https://api.fediverse.observer/
user@host:~$
```

@dmorley is there any documentation on how we can query the api.fediverse.observer API using cURL?

**Comment by dmorley** [comment]
Try

`curl 'https://api.fediverse.observer/' -X POST -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' -H 'Content-Type: application/json' --data-raw '{"query":"query{\n  node (domain: \"lemmy.ml\") {\nuptime_alltime\n  }\n}\n"}'`

It uses Graphql if you want to look at their docs.

**Comment by dmorley** [comment]
You can also pull all lemmy nodes if that suits your need here 

`curl 'https://api.fediverse.observer/' -X POST -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' -H 'Content-Type: application/json' --data-raw '{"query":"query{\n  nodes (softwarename: \"lemmy\") {\ndomain uptime_alltime\n  }\n}\n"}'`

**Comment by maltfield** [comment]
this is done
